import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Starting seed...');

    // Create admin user
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@toletboardchennai.com';
    const adminPassword = process.env.ADMIN_PASSWORD || 'ChangeThisPassword123!';
    const passwordHash = await bcrypt.hash(adminPassword, 10);

    const admin = await prisma.admin.upsert({
        where: { email: adminEmail },
        update: {},
        create: {
            email: adminEmail,
            passwordHash,
        },
    });

    console.log('✅ Admin user created:', admin.email);

    // Create site settings
    const settings = await prisma.siteSettings.upsert({
        where: { id: 'default' },
        update: {},
        create: {
            id: 'default',
            brandName: 'Tolet Board Chennai',
            tagline: '360° Tours • Rent & Lease • Chennai',
            city: 'Chennai',
            whatsappNumber: '+919363393324',
            phoneNumber: '+919363393324',
            whatsappTemplate: 'Hi, I\'m interested in {propertyTitle}. Link: {propertyUrl} - Tolet Board Chennai',
        },
    });

    console.log('✅ Site settings created');

    // Sample properties with full feature data
    const properties = [
        {
            title: '3BHK Premium Apartment in OMR',
            slug: '3bhk-premium-apartment-omr',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Apartment',
            areaName: 'OMR',
            priceInr: 35000,
            sizeSqft: 1450,
            bedrooms: 3,
            bathrooms: 2,
            parking: '2 covered',
            furnishing: 'Semi Furnished',
            floorNumber: 8,
            totalFloors: 14,
            carpetAreaSqft: 1200,
            tenantPreference: 'Family',
            propertyAge: '1-5 Years',
            availableFrom: new Date('2026-03-01'),
            advanceMonths: 3,
            topFacilities: JSON.stringify(['Swimming Pool', 'Gymnasium', 'Club House', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift']),
            locationAdvantages: JSON.stringify([
                { name: 'DPS World School', type: 'School', distance: '1.2 Kms' },
                { name: 'Apollo Hospital', type: 'Hospital', distance: '2.5 Kms' },
                { name: 'Phoenix Mall', type: 'Mall', distance: '3.0 Kms' },
                { name: 'Tidel Park IT', type: 'Office', distance: '4.0 Kms' },
                { name: 'OMR Food Street', type: 'Restaurant', distance: '0.8 Kms' },
                { name: 'Navalur Bus Stop', type: 'Transport', distance: '0.3 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '3 BHK, 2 Baths, Pooja Room' },
                { key: 'Carpet Area', value: '1200 sq.ft.' },
                { key: 'Furnishing', value: 'Semi Furnished' },
                { key: 'Power Backup', value: 'Full' },
                { key: 'Width of Facing Road', value: '60 ft' },
                { key: 'Floor Number', value: '8' },
                { key: 'Flooring', value: 'Vitrified Tiles' },
                { key: 'Facing', value: 'East' },
                { key: 'Wheelchair Friendly', value: 'Yes' },
                { key: 'Rental Agreement Duration', value: '11 months' },
                { key: 'Water Supply', value: 'Corporation + Borewell' },
                { key: 'Balcony', value: '2 (attached to living & master bedroom)' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: true,
        },
        {
            title: 'Luxury Villa in ECR',
            slug: 'luxury-villa-ecr',
            dealType: 'lease',
            usageType: 'residential',
            propertySubtype: 'Villa',
            areaName: 'ECR',
            priceInr: 80000,
            sizeSqft: 2800,
            bedrooms: 4,
            bathrooms: 4,
            parking: '3 covered',
            furnishing: 'Fully Furnished',
            floorNumber: null,
            totalFloors: 2,
            carpetAreaSqft: 2400,
            tenantPreference: 'Family',
            propertyAge: '0-1 Year',
            availableFrom: new Date('2026-04-01'),
            leasePeriodYears: 3,
            topFacilities: JSON.stringify(['Swimming Pool', 'Garden', 'Security', 'Power Backup', 'Water Supply', 'Parking', 'CCTV']),
            locationAdvantages: JSON.stringify([
                { name: 'VGP Universal Kingdom', type: 'Park', distance: '3.2 Kms' },
                { name: 'MGM Healthcare', type: 'Hospital', distance: '8 Kms' },
                { name: 'Kalakshetra Foundation', type: 'School', distance: '2.5 Kms' },
                { name: 'Mahabalipuram Beach', type: 'Landmark', distance: '15 Kms' },
                { name: 'ECR Promenade', type: 'Restaurant', distance: '1.0 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '4 BHK, 4 Baths, Private Garden' },
                { key: 'Carpet Area', value: '2400 sq.ft.' },
                { key: 'Furnishing', value: 'Fully Furnished' },
                { key: 'Power Backup', value: 'Full (Generator + Inverter)' },
                { key: 'Width of Facing Road', value: '40 ft' },
                { key: 'Flooring', value: 'Italian Marble' },
                { key: 'Facing', value: 'South-East' },
                { key: 'Kitchen', value: 'Modular with chimney & appliances' },
                { key: 'Swimming Pool', value: 'Private (20x10 ft)' },
                { key: 'Garden Area', value: '800 sq.ft.' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: '2BHK Apartment in Velachery',
            slug: '2bhk-apartment-velachery',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Apartment',
            areaName: 'Velachery',
            priceInr: 22000,
            sizeSqft: 1100,
            bedrooms: 2,
            bathrooms: 2,
            parking: '1 covered',
            furnishing: 'Semi Furnished',
            floorNumber: 5,
            totalFloors: 11,
            carpetAreaSqft: 900,
            tenantPreference: 'Family',
            propertyAge: '5-10 Years',
            availableFrom: new Date('2026-03-15'),
            advanceMonths: 6,
            topFacilities: JSON.stringify(['Lift', 'Parking', 'Security', 'Power Backup', 'Water Supply', 'Children\'s Play Area']),
            locationAdvantages: JSON.stringify([
                { name: 'Velachery MRTS Station', type: 'Transport', distance: '0.5 Kms' },
                { name: 'Phoenix MarketCity', type: 'Mall', distance: '1.5 Kms' },
                { name: 'SBOA School', type: 'School', distance: '1.0 Kms' },
                { name: 'Vijaya Hospital', type: 'Hospital', distance: '2.0 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '2 BHK, 2 Baths' },
                { key: 'Carpet Area', value: '900 sq.ft.' },
                { key: 'Furnishing', value: 'Semi Furnished' },
                { key: 'Power Backup', value: 'Partial (Inverter)' },
                { key: 'Floor Number', value: '5' },
                { key: 'Flooring', value: 'Vitrified Tiles' },
                { key: 'Facing', value: 'North' },
                { key: 'Water Supply', value: 'Corporation' },
                { key: 'Balcony', value: '1 (attached to living room)' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: 'Commercial Office Space in Adyar',
            slug: 'commercial-office-space-adyar',
            dealType: 'lease',
            usageType: 'commercial',
            propertySubtype: 'Office',
            areaName: 'Adyar',
            priceInr: 120000,
            sizeSqft: 3500,
            bedrooms: null,
            bathrooms: 3,
            parking: '10 open',
            furnishing: 'Fully Furnished',
            floorNumber: 3,
            totalFloors: 6,
            carpetAreaSqft: 3000,
            tenantPreference: 'Anyone',
            propertyAge: '1-5 Years',
            leasePeriodYears: 5,
            topFacilities: JSON.stringify(['Lift', 'Parking', 'Security', 'Power Backup', 'CCTV', 'Cafeteria', 'Conference Room']),
            locationAdvantages: JSON.stringify([
                { name: 'Adyar Bus Depot', type: 'Transport', distance: '0.3 Kms' },
                { name: 'IIT Madras', type: 'Landmark', distance: '2.0 Kms' },
                { name: 'Adyar Ananda Bhavan', type: 'Restaurant', distance: '0.5 Kms' },
                { name: 'Apollo Hospital', type: 'Hospital', distance: '3.5 Kms' },
                { name: 'Adyar Gate', type: 'Landmark', distance: '1.0 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Office Layout', value: '15 Workstations + 2 Cabins + Meeting Room' },
                { key: 'Carpet Area', value: '3000 sq.ft.' },
                { key: 'Furnishing', value: 'Fully Furnished (AC, chairs, desks)' },
                { key: 'Power Backup', value: 'Full (DG Set)' },
                { key: 'Internet', value: 'Fiber Optic Ready' },
                { key: 'Pantry', value: 'Yes (with microwave & fridge)' },
                { key: 'Washrooms', value: '3 per floor' },
                { key: 'Fire Safety', value: 'Sprinklers + extinguishers' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: '1BHK Compact Flat in Anna Nagar',
            slug: '1bhk-compact-flat-anna-nagar',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Apartment',
            areaName: 'Anna Nagar',
            priceInr: 15000,
            sizeSqft: 650,
            bedrooms: 1,
            bathrooms: 1,
            parking: '1 open',
            furnishing: 'Unfurnished',
            floorNumber: 3,
            totalFloors: 5,
            carpetAreaSqft: 550,
            tenantPreference: 'Anyone',
            propertyAge: '10+ Years',
            availableFrom: new Date('2026-02-20'),
            advanceMonths: 3,
            topFacilities: JSON.stringify(['Lift', 'Security', 'Water Supply', 'Power Backup']),
            locationAdvantages: JSON.stringify([
                { name: 'Anna Nagar Tower Park', type: 'Park', distance: '0.8 Kms' },
                { name: 'Shanti Gears School', type: 'School', distance: '1.2 Kms' },
                { name: 'Anna Nagar Metro', type: 'Transport', distance: '0.5 Kms' },
                { name: 'Kaveri Hospital', type: 'Hospital', distance: '1.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '1 BHK, 1 Bath' },
                { key: 'Carpet Area', value: '550 sq.ft.' },
                { key: 'Furnishing', value: 'Unfurnished' },
                { key: 'Power Backup', value: 'Inverter' },
                { key: 'Floor Number', value: '3' },
                { key: 'Flooring', value: 'Mosaic' },
                { key: 'Facing', value: 'West' },
                { key: 'Water Supply', value: 'Corporation + Sump' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: 'Spacious 3BHK in Porur',
            slug: 'spacious-3bhk-porur',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Apartment',
            areaName: 'Porur',
            priceInr: 28000,
            sizeSqft: 1350,
            bedrooms: 3,
            bathrooms: 2,
            parking: '2 covered',
            furnishing: 'Semi Furnished',
            floorNumber: 12,
            totalFloors: 19,
            carpetAreaSqft: 1100,
            tenantPreference: 'Family',
            propertyAge: '1-5 Years',
            availableFrom: new Date('2026-03-10'),
            advanceMonths: 6,
            topFacilities: JSON.stringify(['Lift', 'Parking', 'Security', 'Power Backup', 'Play Area', 'Club House', 'Gym']),
            locationAdvantages: JSON.stringify([
                { name: 'Porur Toll Gate', type: 'Transport', distance: '0.5 Kms' },
                { name: 'Ramachandra Hospital', type: 'Hospital', distance: '2.0 Kms' },
                { name: 'Forum Vijaya Mall', type: 'Mall', distance: '3.5 Kms' },
                { name: 'DAV School Porur', type: 'School', distance: '1.0 Kms' },
                { name: 'Porur Lake', type: 'Park', distance: '1.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '3 BHK, 2 Baths, Utility Area' },
                { key: 'Carpet Area', value: '1100 sq.ft.' },
                { key: 'Furnishing', value: 'Semi Furnished' },
                { key: 'Power Backup', value: 'Full' },
                { key: 'Width of Facing Road', value: '100 ft' },
                { key: 'Floor Number', value: '12' },
                { key: 'Flooring', value: 'Vitrified' },
                { key: 'Facing', value: 'East' },
                { key: 'Wheelchair Friendly', value: 'Yes' },
                { key: 'Rental Agreement Duration', value: '11 months' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: 'Retail Shop in T Nagar',
            slug: 'retail-shop-t-nagar',
            dealType: 'lease',
            usageType: 'commercial',
            propertySubtype: 'Shop',
            areaName: 'T Nagar',
            priceInr: 75000,
            sizeSqft: 800,
            bedrooms: null,
            bathrooms: 1,
            parking: 'Street parking',
            furnishing: 'Unfurnished',
            floorNumber: 0,
            totalFloors: 3,
            carpetAreaSqft: 700,
            tenantPreference: 'Anyone',
            propertyAge: '10+ Years',
            leasePeriodYears: 5,
            topFacilities: JSON.stringify(['Security', 'Power Backup', 'CCTV', 'Water Supply']),
            locationAdvantages: JSON.stringify([
                { name: 'Ranganathan Street', type: 'Landmark', distance: '0.2 Kms' },
                { name: 'T Nagar Bus Stand', type: 'Transport', distance: '0.3 Kms' },
                { name: 'Pondy Bazaar', type: 'Mall', distance: '0.8 Kms' },
                { name: 'Mambalam Railway Station', type: 'Transport', distance: '0.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Shop Type', value: 'Ground Floor Showroom' },
                { key: 'Carpet Area', value: '700 sq.ft.' },
                { key: 'Frontage', value: '25 ft' },
                { key: 'Ceiling Height', value: '12 ft' },
                { key: 'Power Load', value: '10 KW' },
                { key: 'Shutters', value: 'Motorized Rolling' },
                { key: 'Suitable For', value: 'Retail, Showroom, Clinic' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: '2BHK Independent House in Tambaram',
            slug: '2bhk-independent-house-tambaram',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Independent House',
            areaName: 'Tambaram',
            priceInr: 18000,
            sizeSqft: 950,
            bedrooms: 2,
            bathrooms: 2,
            parking: '2 open',
            furnishing: 'Unfurnished',
            floorNumber: null,
            totalFloors: 1,
            carpetAreaSqft: 850,
            tenantPreference: 'Family',
            propertyAge: '5-10 Years',
            availableFrom: new Date('2026-04-01'),
            advanceMonths: 3,
            topFacilities: JSON.stringify(['Parking', 'Water Supply', 'Garden', 'Power Backup']),
            locationAdvantages: JSON.stringify([
                { name: 'Tambaram Railway Station', type: 'Transport', distance: '1.5 Kms' },
                { name: 'Christ University', type: 'School', distance: '2.0 Kms' },
                { name: 'Tambaram Market', type: 'Mall', distance: '1.0 Kms' },
                { name: 'CSI Hospital', type: 'Hospital', distance: '2.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '2 BHK, 2 Baths, Open Terrace' },
                { key: 'Carpet Area', value: '850 sq.ft.' },
                { key: 'Furnishing', value: 'Unfurnished' },
                { key: 'Power Backup', value: 'Inverter' },
                { key: 'Width of Facing Road', value: '30 ft' },
                { key: 'Flooring', value: 'Granite' },
                { key: 'Facing', value: 'North-East' },
                { key: 'Water Supply', value: 'Borewell + Sump' },
                { key: 'Pet Friendly', value: 'Yes' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: 'Premium 4BHK Penthouse in OMR',
            slug: 'premium-4bhk-penthouse-omr',
            dealType: 'lease',
            usageType: 'residential',
            propertySubtype: 'Penthouse',
            areaName: 'OMR',
            priceInr: 95000,
            sizeSqft: 3200,
            bedrooms: 4,
            bathrooms: 4,
            parking: '3 covered',
            furnishing: 'Fully Furnished',
            floorNumber: 18,
            totalFloors: 18,
            carpetAreaSqft: 2800,
            tenantPreference: 'Family',
            propertyAge: '0-1 Year',
            availableFrom: new Date('2026-05-01'),
            leasePeriodYears: 3,
            topFacilities: JSON.stringify(['Lift', 'Parking', 'Security', 'Power Backup', 'Gym', 'Swimming Pool', 'Club House', 'CCTV', 'Rooftop Garden']),
            locationAdvantages: JSON.stringify([
                { name: 'Sholinganallur Signal', type: 'Transport', distance: '1.0 Kms' },
                { name: 'Cognizant Tech Park', type: 'Office', distance: '3.0 Kms' },
                { name: 'Global Hospital', type: 'Hospital', distance: '4.0 Kms' },
                { name: 'Navalur Junction', type: 'Transport', distance: '2.0 Kms' },
                { name: 'Thoraipakkam Lake', type: 'Park', distance: '2.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '4 BHK, 4 Baths, Private Terrace, Pooja Room' },
                { key: 'Carpet Area', value: '2800 sq.ft.' },
                { key: 'Furnishing', value: 'Fully Furnished (Premium)' },
                { key: 'Power Backup', value: 'Full (DG + Inverter)' },
                { key: 'Floor Number', value: 'Top Floor (18th)' },
                { key: 'Flooring', value: 'Italian Marble + Wooden' },
                { key: 'Facing', value: 'East (Sea Breeze)' },
                { key: 'Modular Kitchen', value: 'Yes (Hettich + Chimney)' },
                { key: 'Smart Home', value: 'Alexa-enabled lights & curtains' },
                { key: 'Private Terrace', value: '600 sq.ft. with BBQ area' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: true,
        },
        {
            title: 'Warehouse Space in Ambattur',
            slug: 'warehouse-space-ambattur',
            dealType: 'lease',
            usageType: 'commercial',
            propertySubtype: 'Warehouse',
            areaName: 'Ambattur',
            priceInr: 150000,
            sizeSqft: 8000,
            bedrooms: null,
            bathrooms: 2,
            parking: '20 open',
            furnishing: 'Unfurnished',
            floorNumber: null,
            totalFloors: 1,
            carpetAreaSqft: 7500,
            tenantPreference: 'Anyone',
            propertyAge: '5-10 Years',
            leasePeriodYears: 5,
            topFacilities: JSON.stringify(['Security', 'Power Backup', 'CCTV', 'Loading Dock', 'Water Supply']),
            locationAdvantages: JSON.stringify([
                { name: 'Ambattur Industrial Estate', type: 'Landmark', distance: '0.5 Kms' },
                { name: 'NH-4 Highway', type: 'Transport', distance: '1.0 Kms' },
                { name: 'Ambattur Railway Station', type: 'Transport', distance: '2.0 Kms' },
                { name: 'Padi Junction', type: 'Transport', distance: '3.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Warehouse Type', value: 'Covered Godown' },
                { key: 'Carpet Area', value: '7500 sq.ft.' },
                { key: 'Ceiling Height', value: '25 ft' },
                { key: 'Power Load', value: '50 KW (3 Phase)' },
                { key: 'Loading Bays', value: '2 (truck height)' },
                { key: 'Floor Load Capacity', value: '5 ton/sq.m.' },
                { key: 'Security', value: '24/7 Guard + CCTV' },
                { key: 'Fire Safety', value: 'Sprinklers + NOC' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: 'Cozy Studio Apartment in Velachery',
            slug: 'cozy-studio-apartment-velachery',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Studio',
            areaName: 'Velachery',
            priceInr: 12000,
            sizeSqft: 450,
            bedrooms: 0,
            bathrooms: 1,
            parking: '1 open',
            furnishing: 'Fully Furnished',
            floorNumber: 2,
            totalFloors: 7,
            carpetAreaSqft: 380,
            tenantPreference: 'Single Men',
            propertyAge: '1-5 Years',
            availableFrom: new Date('2026-02-25'),
            advanceMonths: 3,
            topFacilities: JSON.stringify(['Lift', 'Security', 'Water Supply', 'WiFi', 'Laundry']),
            locationAdvantages: JSON.stringify([
                { name: 'Velachery MRTS', type: 'Transport', distance: '0.4 Kms' },
                { name: 'Adyar Gate', type: 'Landmark', distance: '3.0 Kms' },
                { name: 'Chetpet Park', type: 'Park', distance: '5.0 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: 'Studio, 1 Bath' },
                { key: 'Carpet Area', value: '380 sq.ft.' },
                { key: 'Furnishing', value: 'Fully Furnished (Bed, Wardrobe, AC, Washing Machine)' },
                { key: 'Power Backup', value: 'Inverter' },
                { key: 'Floor Number', value: '2' },
                { key: 'Flooring', value: 'Vitrified Tiles' },
                { key: 'Facing', value: 'South' },
                { key: 'Cooking', value: 'Kitchenette with gas stove' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: 'Modern Office in Guindy',
            slug: 'modern-office-guindy',
            dealType: 'lease',
            usageType: 'commercial',
            propertySubtype: 'Office',
            areaName: 'Guindy',
            priceInr: 85000,
            sizeSqft: 2500,
            bedrooms: null,
            bathrooms: 2,
            parking: '8 covered',
            furnishing: 'Fully Furnished',
            floorNumber: 5,
            totalFloors: 10,
            carpetAreaSqft: 2100,
            tenantPreference: 'Anyone',
            propertyAge: '1-5 Years',
            leasePeriodYears: 3,
            topFacilities: JSON.stringify(['Lift', 'Parking', 'Security', 'Power Backup', 'CCTV', 'Cafeteria', 'Conference Room', 'WiFi']),
            locationAdvantages: JSON.stringify([
                { name: 'Guindy Metro Station', type: 'Transport', distance: '0.3 Kms' },
                { name: 'Guindy Industrial Estate', type: 'Landmark', distance: '1.0 Kms' },
                { name: 'Chennai Trade Centre', type: 'Landmark', distance: '2.0 Kms' },
                { name: 'Ekkatuthangal Metro', type: 'Transport', distance: '1.5 Kms' },
                { name: 'Kathipara Junction', type: 'Transport', distance: '2.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Office Layout', value: '20 Workstations + 3 Cabins + Board Room' },
                { key: 'Carpet Area', value: '2100 sq.ft.' },
                { key: 'Furnishing', value: 'Fully Furnished (Herman Miller chairs)' },
                { key: 'Power Backup', value: 'Full (DG Set)' },
                { key: 'Internet', value: 'Leased Line (100 Mbps)' },
                { key: 'Pantry', value: 'Yes (fully equipped)' },
                { key: 'Server Room', value: 'Yes (AC + UPS)' },
                { key: 'Fire Safety', value: 'NOC Compliant' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: '3BHK Sea View Apartment in ECR',
            slug: '3bhk-sea-view-apartment-ecr',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Apartment',
            areaName: 'ECR',
            priceInr: 45000,
            sizeSqft: 1600,
            bedrooms: 3,
            bathrooms: 3,
            parking: '2 covered',
            furnishing: 'Semi Furnished',
            floorNumber: 10,
            totalFloors: 15,
            carpetAreaSqft: 1350,
            tenantPreference: 'Family',
            propertyAge: '0-1 Year',
            availableFrom: new Date('2026-03-20'),
            advanceMonths: 6,
            topFacilities: JSON.stringify(['Lift', 'Parking', 'Security', 'Power Backup', 'Swimming Pool', 'Beach Access', 'Gym', 'Club House']),
            locationAdvantages: JSON.stringify([
                { name: 'Neelankarai Beach', type: 'Landmark', distance: '0.2 Kms' },
                { name: 'Chettinad Hospital', type: 'Hospital', distance: '5.0 Kms' },
                { name: 'American International School', type: 'School', distance: '3.0 Kms' },
                { name: 'Akkarai Beach Road', type: 'Landmark', distance: '1.0 Kms' },
                { name: 'ECR Food Court', type: 'Restaurant', distance: '0.5 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '3 BHK, 3 Baths, Balcony with Sea View' },
                { key: 'Carpet Area', value: '1350 sq.ft.' },
                { key: 'Furnishing', value: 'Semi Furnished' },
                { key: 'Power Backup', value: 'Full' },
                { key: 'Floor Number', value: '10' },
                { key: 'Flooring', value: 'Vitrified Tiles' },
                { key: 'Facing', value: 'East (Sea Facing)' },
                { key: 'Balcony', value: '2 (Sea View + Garden View)' },
                { key: 'Beach Access', value: 'Private gate to beach (2 min walk)' },
                { key: 'Wind', value: 'Natural sea breeze ventilation' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: true,
        },
        {
            title: 'Budget 2BHK in Chromepet',
            slug: 'budget-2bhk-chromepet',
            dealType: 'rent',
            usageType: 'residential',
            propertySubtype: 'Apartment',
            areaName: 'Chromepet',
            priceInr: 14000,
            sizeSqft: 850,
            bedrooms: 2,
            bathrooms: 1,
            parking: '1 open',
            furnishing: 'Unfurnished',
            floorNumber: 1,
            totalFloors: 4,
            carpetAreaSqft: 720,
            tenantPreference: 'Anyone',
            propertyAge: '10+ Years',
            availableFrom: new Date('2026-03-01'),
            advanceMonths: 3,
            topFacilities: JSON.stringify(['Water Supply', 'Security', 'Power Backup']),
            locationAdvantages: JSON.stringify([
                { name: 'Chromepet Railway Station', type: 'Transport', distance: '0.5 Kms' },
                { name: 'Chromepet Bus Depot', type: 'Transport', distance: '0.3 Kms' },
                { name: 'SRM Hospital', type: 'Hospital', distance: '3.0 Kms' },
                { name: 'Hastinapuram Market', type: 'Mall', distance: '1.0 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Layout', value: '2 BHK, 1 Bath' },
                { key: 'Carpet Area', value: '720 sq.ft.' },
                { key: 'Furnishing', value: 'Unfurnished' },
                { key: 'Power Backup', value: 'None (can install inverter)' },
                { key: 'Floor Number', value: '1' },
                { key: 'Flooring', value: 'Mosaic' },
                { key: 'Facing', value: 'North' },
                { key: 'Water Supply', value: 'Corporation + Overhead Tank' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
        {
            title: 'Co-working Space in Nungambakkam',
            slug: 'coworking-space-nungambakkam',
            dealType: 'lease',
            usageType: 'commercial',
            propertySubtype: 'Co-working',
            areaName: 'Nungambakkam',
            priceInr: 50000,
            sizeSqft: 1500,
            bedrooms: null,
            bathrooms: 3,
            parking: '5 covered',
            furnishing: 'Fully Furnished',
            floorNumber: 4,
            totalFloors: 8,
            carpetAreaSqft: 1300,
            tenantPreference: 'Anyone',
            propertyAge: '0-1 Year',
            leasePeriodYears: 2,
            topFacilities: JSON.stringify(['Lift', 'Parking', 'Security', 'Power Backup', 'CCTV', 'WiFi', 'Cafeteria', 'Meeting Rooms']),
            locationAdvantages: JSON.stringify([
                { name: 'Nungambakkam Railway Station', type: 'Transport', distance: '0.5 Kms' },
                { name: 'Express Avenue Mall', type: 'Mall', distance: '2.0 Kms' },
                { name: 'Apollo Hospital Greams Rd', type: 'Hospital', distance: '1.0 Kms' },
                { name: 'Sterling Road', type: 'Landmark', distance: '0.8 Kms' },
                { name: 'Nungambakkam High Road', type: 'Landmark', distance: '0.2 Kms' },
            ]),
            propertyDetails: JSON.stringify([
                { key: 'Space Type', value: 'Open Plan + 4 Private Cabins' },
                { key: 'Carpet Area', value: '1300 sq.ft.' },
                { key: 'Furnishing', value: 'Fully Furnished (Ergonomic setup)' },
                { key: 'Power Backup', value: 'Full (DG + UPS)' },
                { key: 'Internet', value: 'Fiber 200 Mbps + Backup Line' },
                { key: 'Pantry', value: 'Yes (tea, coffee, water dispenser)' },
                { key: 'Meeting Rooms', value: '2 (8-seater + 4-seater)' },
                { key: 'Common Area', value: 'Lounge + Phone Booths' },
                { key: 'Working Hours', value: '24/7 Access' },
            ]),
            tourEmbedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            isPublished: true,
            isFeatured: false,
        },
    ];

    for (let i = 0; i < properties.length; i++) {
        const property = properties[i];
        // Add placeholder thumbnail images for each property
        const imageId1 = 100 + i * 3;
        const imageId2 = 101 + i * 3;
        const propertyWithImages = {
            ...property,
            images: JSON.stringify([
                `https://picsum.photos/seed/prop${imageId1}/800/600`,
                `https://picsum.photos/seed/prop${imageId2}/800/600`,
            ]),
        };
        await prisma.property.upsert({
            where: { slug: property.slug },
            update: propertyWithImages,
            create: propertyWithImages,
        });
    }

    console.log(`✅ Created ${properties.length} properties`);
    console.log('🎉 Seed completed successfully!');
}

main()
    .catch((e) => {
        console.error('❌ Seed failed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
