// Comprehensive list of Chennai areas/localities
// Sourced from 99acres, NoBroker, MagicBricks

export const CHENNAI_AREAS: string[] = [
    // North Chennai
    'Ambattur',
    'Anna Nagar',
    'Anna Nagar East',
    'Anna Nagar West',
    'Ayanavaram',
    'Basin Bridge',
    'Ennore',
    'Erukkancheri',
    'George Town',
    'Kolathur',
    'Korukkupet',
    'Madhavaram',
    'Manali',
    'Mannady',
    'Minjur',
    'Mogappair',
    'Mogappair East',
    'Mogappair West',
    'Padi',
    'Paruthipattu',
    'Perambur',
    'Ponneri',
    'Puzhal',
    'Red Hills',
    'Redhills',
    'Royapuram',
    'Sowcarpet',
    'Thirumullaivoyal',
    'Tiruvottiyur',
    'Tondiarpet',
    'Villivakkam',
    'Vyasarpadi',
    'Washermanpet',

    // Central Chennai
    'Alwarpet',
    'Arumbakkam',
    'Ashok Nagar',
    'Chetpet',
    'Egmore',
    'Kilpauk',
    'Kodambakkam',
    'Koyambedu',
    'Mambalam',
    'Mylapore',
    'Nungambakkam',
    'Purasawalkam',
    'Saidapet',
    'Saligramam',
    'T. Nagar',
    'Teynampet',
    'Thousand Lights',
    'Vadapalani',
    'Valasaravakkam',
    'West Mambalam',

    // South Chennai
    'Adambakkam',
    'Adyar',
    'Besant Nagar',
    'Camp Road',
    'Chromepet',
    'East Coast Road (ECR)',
    'Egattur',
    'Guindy',
    'Guduvancheri',
    'Injambakkam',
    'Jalladianpet',
    'Karapakkam',
    'Kelambakkam',
    'Keelkattalai',
    'Kovilambakkam',
    'Madipakkam',
    'Medavakkam',
    'Muttukadu',
    'Nanganallur',
    'Navalur',
    'Neelankarai',
    'Old Mahabalipuram Road (OMR)',
    'Padur',
    'Palavakkam',
    'Pallavaram',
    'Pallikaranai',
    'Pammal',
    'Perumbakkam',
    'Perungudi',
    'Porur',
    'Raja Annamalai Puram',
    'Ramapuram',
    'Selaiyur',
    'Sembakkam',
    'Semmancheri',
    'Sholinganallur',
    'Siruseri',
    'St. Thomas Mount',
    'Taramani',
    'Tambaram',
    'Tambaram East',
    'Tambaram West',
    'Thiruvanmiyur',
    'Thoraipakkam',
    'Urapakkam',
    'Vandalur',
    'Velachery',
    'Vettuvankeni',

    // West Chennai
    'Alapakkam',
    'Avadi',
    'Gerugambakkam',
    'Iyyappanthangal',
    'KK Nagar',
    'Kundrathur',
    'Maduravoyal',
    'Mangadu',
    'Manapakkam',
    'Nesapakkam',
    'Poonamallee',
    'Porur',
    'Ramachandra Nagar',
    'Virugambakkam',

    // IT Corridor / OMR
    'Kandanchavadi',
    'Kottivakkam',
    'Navalur',
    'Okkiyam Thoraipakkam',
    'Perungudi',
    'Sholinganallur',
    'Siruseri',
    'Thalambur',

    // ECR & Beach Areas
    'Akkarai',
    'Kovalam',
    'Muttukadu',
    'Neelankarai',
    'Thiruvidanthai',
    'Uthandi',

    // Other Important Areas
    'Alandur',
    'Aminjikarai',
    'Chengalpattu',
    'Choolaimedu',
    'Ekkatuthangal',
    'GST Road',
    'ICF Colony',
    'Irungattukottai',
    'Kalavakkam',
    'Korattur',
    'Maraimalai Nagar',
    'Meenambakkam',
    'Mount Road',
    'Mugalivakkam',
    'Nandambakkam',
    'Nandanam',
    'Old Washermanpet',
    'Otteri',
    'Palavanthangal',
    'Potheri',
    'Puzhuthivakkam',
    'Royapettah',
    'Sithalapakkam',
    'Sriperumbudur',
    'Thiruverkadu',
    'Tirusulam',
    'Triplicane',
    'Trustpuram',
    'Urapakkam',
    'Vengaivasal',
    'Virugambakkam',
    'Zamin Pallavaram',
].filter((v, i, a) => a.indexOf(v) === i).sort(); // Deduplicate and sort
